# Generated by Django 5.0.4 on 2025-03-29 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='co_authors',
            field=models.ManyToManyField(blank=True, related_name='coauthor_books', to='main_app.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='main_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_author_books', to='main_app.author'),
        ),
    ]
