# Generated by Django 5.0.4 on 2025-02-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20250222_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.IntegerField(unique=True),
        ),
    ]
