# Generated by Django 5.0.4 on 2025-03-18 12:17

from django.db import migrations

def set_rarity(apps, schema_editor):
    ItemModel = apps.get_model('main_app', 'Item')
    items = ItemModel.objects.all()
    for item in items:
        if item.price <= 10:
            item.rarity = "Rare"
        elif 11 <= item.price <= 20:
            item.rarity = "Very Rare"
        elif 21 <= item.price <= 30:
            item.rarity = "Extremely Rare"
        else:
            item.rarity = "Mega Rare"
            item.save()


def revert_rarity(apps, schema_editor):
    ItemModel = apps.get_model('main_app', 'Item')
    default_item_rarity = ItemModel._meta.get_field('rarity').default
    for item in ItemModel.objects.all():
        item.rarity = default_item_rarity
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_item'),
    ]

    operations = [migrations.RunPython(code=set_rarity, reverse_code=revert_rarity),]

