# Generated by Django 5.0.4 on 2025-03-18 12:29

from django.db import migrations


def migrate_price(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')
    smartphones = SmartphoneModel.objects.all()
    for item in smartphones:
        item.price = len(item.brand) * 120
        item.save()


def revert_price(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')
    default_smartphone_price = SmartphoneModel._meta.get_field('price').default
    SmartphoneModel.objects.update(price=default_smartphone_price)


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0010_smartphone'),
    ]

    operations = [migrations.RunPython(code=migrate_price, reverse_code=revert_price), ]
