# Generated by Django 5.0.4 on 2025-03-18 12:58
from datetime import timedelta

from django.db import migrations


def update_delivery_and_warranty(apps, schema_editor):
    OrderModel = apps.get_model('main_app', 'Order')
    for order in OrderModel.objects.all():
        if order.status == OrderModel.STATUS_CHOICES.Pending:
            order.delivery = order.order_date + timedelta(days=3)
            order.save()
        elif order.status == OrderModel.STATUS_CHOICES.Completed:
            order.warranty = "24 months"
            order.save()
        elif order.status == OrderModel.STATUS_CHOICES.Canceled:
            order.delete()


def reverse_delivery_and_warranty(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_order'),
    ]

    operations = [migrations.RunPython(code=update_delivery_and_warranty, reverse_code=reverse_delivery_and_warranty),]

