# Generated by Django 5.0.4 on 2025-03-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_laptop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dungeon',
            name='difficulty',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=10),
        ),
    ]
