# Generated by Django 5.0.4 on 2025-03-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_dungeon_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dungeon',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10),
        ),
    ]
