# Generated by Django 5.0.4 on 2025-03-29 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_book_co_authors_alter_book_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='co_authors',
            field=models.ManyToManyField(related_name='co_authors_books', to='main_app.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Nonfiction'), ('Other', 'Other')], default='Other', max_length=11),
        ),
        migrations.AlterField(
            model_name='book',
            name='main_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_author_books', to='main_app.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
