# Generated by Django 5.0.4 on 2025-02-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='last_edited',
            new_name='last_edited_on',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='email',
            new_name='email_address',
        ),
        migrations.AlterField(
            model_name='department',
            name='employees_count',
            field=models.IntegerField(default=1, verbose_name='Employee Count'),
        ),
        migrations.AlterField(
            model_name='department',
            name='location',
            field=models.CharField(blank=True, choices=[('Sofia', 'Sofia'), ('Plovdiv', 'Plovdiv'), ('Burgas', 'Burgas'), ('Varna', 'Varna')], max_length=20, null=True),
        ),
    ]
