# Generated by Django 5.0.4 on 2025-03-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'Enter a valid email address'}, max_length=254),
        ),
    ]
